default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres
  host: localhost
  port: 5432
  schema_search_path: extcare,public  
  variables:
    timezone: America/Los_Angeles

development:
  <<: *default
  database: tccs_extcare_development

test:
  <<: *default
  database: tccs_extcare_test

production:
  <<: *default
  database: neondb
  username: extcare
  password: <%= ENV["EXTCARE_DATABASE_PASSWORD"] %>
