default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres
  host: localhost
  port: 5432
  schema_search_path: extcare
  variables:
    timezone: America/Los_Angeles

development:
  <<: *default
  # Avoid macOS GSS initialization in forked Rails test workers.
  gssencmode: disable
  database: tccs_extcare_development

test:
  <<: *default
  gssencmode: disable
  database: tccs_extcare_test

production:
  <<: *default
  database: neondb
  username: extcare
  host: <%= ENV["EXTCARE_DATABASE_HOST"] %>
  password: <%= ENV["EXTCARE_DATABASE_PASSWORD"] %>
  sslmode: require
