// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type Admin struct {
	ID           int64     `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type Attendance struct {
	ID             int64      `json:"id"`
	StudentID      string     `json:"student_id"`
	AttendanceDate time.Time  `json:"attendance_date"`
	CheckinAt      time.Time  `json:"checkin_at"`
	CheckoutAt     *time.Time `json:"checkout_at"`
	CreatedAt      time.Time  `json:"created_at"`
	UpdatedAt      time.Time  `json:"updated_at"`
}

type Session struct {
	ID        int64     `json:"id"`
	AdminID   int64     `json:"admin_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type Student struct {
	ID        int64     `json:"id"`
	StudentID string    `json:"student_id"`
	Name      string    `json:"name"`
	Grade     string    `json:"grade"`
	Active    bool      `json:"active"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
