// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"time"
)

const checkoutAttendance = `-- name: CheckoutAttendance :one
UPDATE attendance
SET checkout_at = $3, updated_at = now()
WHERE student_id = $1 AND attendance_date = $2 AND checkout_at IS NULL
RETURNING id, student_id, attendance_date, checkin_at, checkout_at, created_at, updated_at
`

type CheckoutAttendanceParams struct {
	StudentID      string     `json:"student_id"`
	AttendanceDate time.Time  `json:"attendance_date"`
	CheckoutAt     *time.Time `json:"checkout_at"`
}

func (q *Queries) CheckoutAttendance(ctx context.Context, arg CheckoutAttendanceParams) (Attendance, error) {
	row := q.db.QueryRow(ctx, checkoutAttendance, arg.StudentID, arg.AttendanceDate, arg.CheckoutAt)
	var i Attendance
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.AttendanceDate,
		&i.CheckinAt,
		&i.CheckoutAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countAdmins = `-- name: CountAdmins :one
SELECT count(*)::bigint AS count FROM admins
`

func (q *Queries) CountAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAdmin = `-- name: CreateAdmin :one
INSERT INTO admins (email, password_hash)
VALUES ($1, $2)
RETURNING id, email, password_hash, created_at, updated_at
`

type CreateAdminParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateAdmin(ctx context.Context, arg CreateAdminParams) (Admin, error) {
	row := q.db.QueryRow(ctx, createAdmin, arg.Email, arg.PasswordHash)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAttendance = `-- name: CreateAttendance :one
INSERT INTO attendance (student_id, attendance_date, checkin_at)
VALUES ($1, $2, $3)
RETURNING id, student_id, attendance_date, checkin_at, checkout_at, created_at, updated_at
`

type CreateAttendanceParams struct {
	StudentID      string    `json:"student_id"`
	AttendanceDate time.Time `json:"attendance_date"`
	CheckinAt      time.Time `json:"checkin_at"`
}

func (q *Queries) CreateAttendance(ctx context.Context, arg CreateAttendanceParams) (Attendance, error) {
	row := q.db.QueryRow(ctx, createAttendance, arg.StudentID, arg.AttendanceDate, arg.CheckinAt)
	var i Attendance
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.AttendanceDate,
		&i.CheckinAt,
		&i.CheckoutAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (admin_id, token_hash, expires_at)
VALUES ($1, $2, $3)
`

type CreateSessionParams struct {
	AdminID   int64     `json:"admin_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession, arg.AdminID, arg.TokenHash, arg.ExpiresAt)
	return err
}

const createStudent = `-- name: CreateStudent :one
INSERT INTO students (student_id, name, grade)
VALUES ($1, $2, $3)
RETURNING id, student_id, name, grade, active, created_at, updated_at
`

type CreateStudentParams struct {
	StudentID string `json:"student_id"`
	Name      string `json:"name"`
	Grade     string `json:"grade"`
}

func (q *Queries) CreateStudent(ctx context.Context, arg CreateStudentParams) (Student, error) {
	row := q.db.QueryRow(ctx, createStudent, arg.StudentID, arg.Name, arg.Grade)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.Name,
		&i.Grade,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAdmin = `-- name: DeleteAdmin :execrows
DELETE FROM admins
WHERE id = $1
`

func (q *Queries) DeleteAdmin(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAdmin, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions
WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteSessionByTokenHash = `-- name: DeleteSessionByTokenHash :exec
DELETE FROM sessions
WHERE token_hash = $1
`

func (q *Queries) DeleteSessionByTokenHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteSessionByTokenHash, tokenHash)
	return err
}

const getAdminByEmail = `-- name: GetAdminByEmail :one
SELECT id, email, password_hash, created_at, updated_at
FROM admins
WHERE email = $1
`

func (q *Queries) GetAdminByEmail(ctx context.Context, email string) (Admin, error) {
	row := q.db.QueryRow(ctx, getAdminByEmail, email)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdminByID = `-- name: GetAdminByID :one
SELECT id, email, password_hash, created_at, updated_at
FROM admins
WHERE id = $1
`

func (q *Queries) GetAdminByID(ctx context.Context, id int64) (Admin, error) {
	row := q.db.QueryRow(ctx, getAdminByID, id)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAttendance = `-- name: GetAttendance :one
SELECT id, student_id, attendance_date, checkin_at, checkout_at, created_at, updated_at
FROM attendance
WHERE student_id = $1 AND attendance_date = $2
`

type GetAttendanceParams struct {
	StudentID      string    `json:"student_id"`
	AttendanceDate time.Time `json:"attendance_date"`
}

func (q *Queries) GetAttendance(ctx context.Context, arg GetAttendanceParams) (Attendance, error) {
	row := q.db.QueryRow(ctx, getAttendance, arg.StudentID, arg.AttendanceDate)
	var i Attendance
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.AttendanceDate,
		&i.CheckinAt,
		&i.CheckoutAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAttendanceForUpdate = `-- name: GetAttendanceForUpdate :one
SELECT id, student_id, attendance_date, checkin_at, checkout_at, created_at, updated_at
FROM attendance
WHERE student_id = $1 AND attendance_date = $2
FOR UPDATE
`

type GetAttendanceForUpdateParams struct {
	StudentID      string    `json:"student_id"`
	AttendanceDate time.Time `json:"attendance_date"`
}

func (q *Queries) GetAttendanceForUpdate(ctx context.Context, arg GetAttendanceForUpdateParams) (Attendance, error) {
	row := q.db.QueryRow(ctx, getAttendanceForUpdate, arg.StudentID, arg.AttendanceDate)
	var i Attendance
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.AttendanceDate,
		&i.CheckinAt,
		&i.CheckoutAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT s.admin_id, s.expires_at, a.email
FROM sessions s
JOIN admins a ON a.id = s.admin_id
WHERE s.token_hash = $1
`

type GetSessionByTokenHashRow struct {
	AdminID   int64     `json:"admin_id"`
	ExpiresAt time.Time `json:"expires_at"`
	Email     string    `json:"email"`
}

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash string) (GetSessionByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i GetSessionByTokenHashRow
	err := row.Scan(&i.AdminID, &i.ExpiresAt, &i.Email)
	return i, err
}

const getStudentByStudentID = `-- name: GetStudentByStudentID :one
SELECT id, student_id, name, grade, active, created_at, updated_at
FROM students
WHERE student_id = $1
`

func (q *Queries) GetStudentByStudentID(ctx context.Context, studentID string) (Student, error) {
	row := q.db.QueryRow(ctx, getStudentByStudentID, studentID)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.Name,
		&i.Grade,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveStudents = `-- name: ListActiveStudents :many
SELECT id, student_id, name, grade, active, created_at, updated_at
FROM students
WHERE active
ORDER BY name ASC
`

func (q *Queries) ListActiveStudents(ctx context.Context) ([]Student, error) {
	rows, err := q.db.Query(ctx, listActiveStudents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Student{}
	for rows.Next() {
		var i Student
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.Name,
			&i.Grade,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdmins = `-- name: ListAdmins :many
SELECT id, email, created_at
FROM admins
ORDER BY email
`

type ListAdminsRow struct {
	ID        int64     `json:"id"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) ListAdmins(ctx context.Context) ([]ListAdminsRow, error) {
	rows, err := q.db.Query(ctx, listAdmins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminsRow{}
	for rows.Next() {
		var i ListAdminsRow
		if err := rows.Scan(&i.ID, &i.Email, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttendanceForDate = `-- name: ListAttendanceForDate :many
SELECT
    a.id,
    a.student_id,
    a.attendance_date,
    a.checkin_at,
    a.checkout_at,
    s.name,
    s.grade
FROM attendance a
JOIN students s ON s.student_id = a.student_id
WHERE a.attendance_date = $1
ORDER BY s.name ASC
`

type ListAttendanceForDateRow struct {
	ID             int64      `json:"id"`
	StudentID      string     `json:"student_id"`
	AttendanceDate time.Time  `json:"attendance_date"`
	CheckinAt      time.Time  `json:"checkin_at"`
	CheckoutAt     *time.Time `json:"checkout_at"`
	Name           string     `json:"name"`
	Grade          string     `json:"grade"`
}

func (q *Queries) ListAttendanceForDate(ctx context.Context, attendanceDate time.Time) ([]ListAttendanceForDateRow, error) {
	rows, err := q.db.Query(ctx, listAttendanceForDate, attendanceDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAttendanceForDateRow{}
	for rows.Next() {
		var i ListAttendanceForDateRow
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.AttendanceDate,
			&i.CheckinAt,
			&i.CheckoutAt,
			&i.Name,
			&i.Grade,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudents = `-- name: ListStudents :many
SELECT id, student_id, name, grade, active, created_at, updated_at
FROM students
ORDER BY active DESC, name ASC
`

func (q *Queries) ListStudents(ctx context.Context) ([]Student, error) {
	rows, err := q.db.Query(ctx, listStudents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Student{}
	for rows.Next() {
		var i Student
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.Name,
			&i.Grade,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setStudentActive = `-- name: SetStudentActive :one
UPDATE students
SET active = $2, updated_at = now()
WHERE id = $1
RETURNING id, student_id, name, grade, active, created_at, updated_at
`

type SetStudentActiveParams struct {
	ID     int64 `json:"id"`
	Active bool  `json:"active"`
}

func (q *Queries) SetStudentActive(ctx context.Context, arg SetStudentActiveParams) (Student, error) {
	row := q.db.QueryRow(ctx, setStudentActive, arg.ID, arg.Active)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.Name,
		&i.Grade,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateStudent = `-- name: UpdateStudent :one
UPDATE students
SET name = $2, grade = $3, updated_at = now()
WHERE id = $1
RETURNING id, student_id, name, grade, active, created_at, updated_at
`

type UpdateStudentParams struct {
	ID    int64  `json:"id"`
	Name  string `json:"name"`
	Grade string `json:"grade"`
}

func (q *Queries) UpdateStudent(ctx context.Context, arg UpdateStudentParams) (Student, error) {
	row := q.db.QueryRow(ctx, updateStudent, arg.ID, arg.Name, arg.Grade)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.Name,
		&i.Grade,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
